version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data_todo:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
    - "${DB_PORT}:5432"
    env_file:
    - ./.env

#  frontend:
#    build: ./todo-list-frontend/.
#    volumes:
#      - frontend_todo:/app/result_build
#    depends_on:
#      - db
#    ports:
#      - "3000:3000"
#      - "8000:8000"


volumes:
  postgres_data_todo:
#  frontend_todo: