# Generated by Django 4.0.3 on 2022-05-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', related_query_name='goals', to='goals.goalcategory', verbose_name='Категория'),
        ),
    ]
