# Generated by Django 4.0.3 on 2022-06-12 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='TgUser',
        ),
    ]
